### ISSUE TITLE
Add a leadership section

### ISSUE THREAD

**Issue by Seb-Robochoa** [gamemanual0/gm0#100]
I was told by Jaxon to open this up. I wrote a leadership page that you guys seemed to like, and I'd like to suggest it as an addition to GM0. 
- Seb #2281

**Comment by dansman805** [comment]
Link to google doc: https://docs.google.com/document/d/18laPq370789iYIrtPU-9z5wBZC3lpDf_wEIOkvU5QK0/edit

**Comment by abidingabi** [comment]
This is out of scope for gm0
