### ISSUE TITLE
Telemetry feature documentation

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#101]
**What information should be added?**
Document telemetry features
- Supported telemetry tags w/examples
- Monospace telemetry, etc.
- Changing transmission interval
- telemetry.speak()

**Does it need it's own page? (Yes/No):** No(?)

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
Under "Using the SDK" maybe?

**Comment by NoahBres** [comment]
`addLine` vs `addData`

**Comment by NoahBres** [comment]
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/text/Html.java#791

Supported tags:

- `<br>` (doesnt actually do anything)
- `<p>`
- `<ul>`
- `<li>`
- `<div>`
- `<span>`
- `<strong>`
  - `<b>` (does the same thing)
- `<em>`
  - `<cite>`
  - `<dfn>`
  - `<i>`
  - (all of these just italicize)
- `<big>`
- `<small>`
- `<blockquote>`
  - seems to just be a wrapping element like span
- `<font>`
  - also seems to just be a wrapping element like span?
- `<tt>`
  - monospace wrapper
- `<a>`
  - it doesnt look like it uses an actual link in the source? so it's just a wrapper element like span?
- `<u>`
  - underline
- `<del>`
  - `<s>`
  - `<strike>`
  - all strikethrough elements
- `<sup>`
  - superscript
- `<sub>`
  - subscript
- `<img>`
  - img doesnt actually do anything. the src attribute seems to exist only to be handled on the android app side and because we dont have access to the DS we can't do anything with it
- `<h1-h6>` tags

None of these have been tested

**Comment by NoahBres** [comment]
`<font size="..." color="..." face="...">`

https://www.techonthenet.com/html/elements/font_tag.php

size = relative size? like `size="+1"`
needs to be tested

color = "string" hex or named colors
source looks like it supports hex and then only a few named colors.
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/text/Html.java#694
needs to be tested

face = "string"
needs to be tested. "monospace" works as a value for sure.
I believe it should support generic-family and family-family from here: https://www.techonthenet.com/css/properties/font_family.php
it seems to just pass the string value into an android font object https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/text/Html.java#1153
so im betting it's fairly flexible

**Comment by NoahBres** [comment]
`<div>` seems to support an align "start", "center", or "end"
not entirely sure how this works. would depend on the width that the div tag takes up. if it fills an entire line these would work as expected. needs to be tested.

**Comment by NoahBres** [comment]
https://github.com/OpenFTC/Extracted-RC/blob/6720cf8b4296c90b6ea4638752c2df4a52b043b9/RobotCore/src/main/java/org/firstinspires/ftc/robotcore/external/Telemetry.java#L542

`DisplayFormat` options `CLASSIC`, `MONOSPACE`, `HTML`

**Comment by NoahBres** [comment]
https://github.com/OpenFTC/Extracted-RC/blob/6720cf8b4296c90b6ea4638752c2df4a52b043b9/RobotCore/src/main/java/org/firstinspires/ftc/robotcore/external/Telemetry.java#L79

This sample is interesting. Never seen it used before.

**Comment by NoahBres** [comment]
https://github.com/OpenFTC/Extracted-RC/blob/6720cf8b4296c90b6ea4638752c2df4a52b043b9/RobotCore/src/main/java/org/firstinspires/ftc/robotcore/external/Telemetry.java#L104

> Actual transmission to the driver station is throttled to avoid use of excessive bandwidth.
> By default, transmission will occur at most every 250ms. This interval can be controlled with
 > {@link #setMsTransmissionInterval(int) setMsTransmissionInterval()}. Any {@link #update()}s which
> occur more frequently will not be transmitted if superseded by a subsequent {@link #update()}
> before the transmission interval expires.</p>

**Comment by NoahBres** [comment]
https://github.com/OpenFTC/Extracted-RC/blob/6720cf8b4296c90b6ea4638752c2df4a52b043b9/RobotCore/src/main/java/org/firstinspires/ftc/robotcore/external/Telemetry.java#L137

![Screen Shot 2021-02-23 at 9 32 56 PM](https://user-images.githubusercontent.com/6739076/108943559-b2746100-761e-11eb-9d27-a193621d1a96.jpg)

**Comment by NoahBres** [comment]
`clear()` vs `clearAll()`

The telemetry api is lowkey not very straightforward because of the fancy stuff they added

**Comment by NoahBres** [comment]
`Telemetry#speak()`

**Comment by NoahBres** [comment]
The telemetry api is sooo over-engineered 

![Screen Shot 2021-02-23 at 9 36 47 PM](https://user-images.githubusercontent.com/6739076/108943874-3b8b9800-761f-11eb-9eba-182e51fe2a21.jpg)

**Comment by NoahBres** [comment]
Items can have captions

![Screen Shot 2021-02-23 at 9 37 27 PM](https://user-images.githubusercontent.com/6739076/108943939-53fbb280-761f-11eb-9f29-767b94d018b8.jpg)

**Comment by dansman805** [comment]
Realistically, when this is worked on, we should definitely write something containing just `addData`, *maybe* `addLine`, transmission interval, and monospace/html. Telemetry is very complicated, but a significant majority of the value of it can be obtained from those few things.

**Comment by NoahAndrews** [comment]
I would add `speak()` to that list, as it adds significant value that can't be approximated using other APIs.
