### ISSUE TITLE
Add Ryan's Road Runner Lite to Control Loop Page

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#105]
**What information should be added?**
Add this to the motion profile section of the control loop page. 
https://mybinder.org/v2/gh/acmerobotics/road-runner/HEAD?filepath=doc%2Fnotebook%2Froad-runner-lite.ipynb

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
software/control loops

**Comment by Eeshwar-Krishnan** [comment]
Closed by #235
