### ISSUE TITLE
Gamepad Diagrams

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#114]
**What information should be added?**
Gamepad diagrams
Ideally for all 3 of the supported gamepad (etpack is just a dualshock clone so can be excluded, plus it's ugly): Xbox 360, Dualshock 4, and Logitech F310

A list of the button aliases would be nice (what originally prompted me to make this issue)

Miscellaneous detail like touchpad button not having an alias.

**Does it need it's own page? (Yes/No):** Idk

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
🤷

**Comment by NoahBres** [comment]
Relevant for aliases: https://github.com/OpenFTC/Extracted-RC/blob/6720cf8b4296c90b6ea4638752c2df4a52b043b9/RobotCore/src/main/java/com/qualcomm/robotcore/hardware/Gamepad.java#L767

**Comment by dansman805** [comment]
Include positive/negative directions on joysticks (up is negative, left is negative, down is positive, right is positive)

**Comment by ajtrowell** [comment]
![blank_white](https://user-images.githubusercontent.com/12280907/107842303-cf3fa780-6d87-11eb-92aa-1e5ba70ec16c.jpg)
![PrintScaled](https://user-images.githubusercontent.com/12280907/107842305-d666b580-6d87-11eb-8a21-4e485606e693.png)

**Comment by shaunsingh** [comment]
![image](https://user-images.githubusercontent.com/71196912/107842927-e46f0300-6d94-11eb-83a0-a763ae138f81.png)

![image](https://user-images.githubusercontent.com/71196912/107842951-04062b80-6d95-11eb-9d81-61d9610e69d3.png)

They don't look as good as the top two images but most diagrams are of ps3 dualshocks

**Comment by dansman805** [comment]
https://commons.wikimedia.org/wiki/File:360_controller.svg
