### ISSUE TITLE
Styling Tweaks

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#128]
Various styling tweaks I think would be appropriate

- Increase heading font weights
  - h1: 500
  - h2: 400
- List styling
  - Padding left for lists so they don't align with headings
  - Margin below each image in a list 
  -  ![image](https://user-images.githubusercontent.com/6739076/106352590-fd15ee00-62a9-11eb-85a6-b6b124e1b228.png)

- Note block tweaks
  - idk why but this looks off to me
  - ![image](https://user-images.githubusercontent.com/6739076/106352617-28004200-62aa-11eb-8fbf-2d53435cdb53.png)

**Comment by NoahBres** [comment]
![Screen Shot 2021-01-30 at 3 27 17 AM](https://user-images.githubusercontent.com/6739076/106352728-10758900-62ab-11eb-986c-a819dd653df2.jpg)

These sections all blend together. Increase division somehow. Increasing font weight for heading may be enough.

**Comment by NoahBres** [comment]
Improve inline code. There's like no contrast between the background of the inline code and the white background. Maybe more padding

![Screen Shot 2021-01-30 at 3 33 52 AM](https://user-images.githubusercontent.com/6739076/106352860-fab49380-62ab-11eb-8b18-1fff2ff2a4b9.jpg)

**Comment by NoahBres** [comment]
![Screen Shot 2021-01-30 at 1 03 02 PM](https://user-images.githubusercontent.com/6739076/106365473-7d187400-62fb-11eb-8c8f-0669fbc97cc5.jpg)

Linked terms mix different underlines.

**Comment by dansman805** [comment]
> Linked terms mix different underlines.
Most of those are glossary items and therefore show something on hover; normal links do not and therefore do not get an underline. Now, whether that's a good thing, :shrug:
