### ISSUE TITLE
Add wireless config format/sample file

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#129]
**What information should be added?**
For the `wireless-configuration` section in `using-android-studio`, paste a sample xml file or explain the general template.

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
/software/using-android-studio.html#wireless-configuration

**Comment by NoahBres** [comment]
This might need to be its own page. It would be neat to document all the possible XML options so a user could write their own config from scratch.

**Comment by abidingabi** [comment]
This is out of scope for gm0
