### ISSUE TITLE
Lift stringing

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#136]
**What information should be added?**
Step by step lift guide.
From lift basics to stringing.
Video medium would be great tbh.

**Does it need it's own page? (Yes/No):** ? Possibly under rigging

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
robot-design/linear-motion-guide/rigging?
Unsure
Might merit it's own guide.

**Comment by abidingabi** [comment]
Closed by #283
