### ISSUE TITLE
Vuforia Localization API

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#143]
**What information should be added?**
Find someone who actually knows how to use it. I don't know enough about it to expound on any details. 

**Does it need it's own page? (Yes/No):** Probably.

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
🤷

**Comment by Eeshwar-Krishnan** [comment]
I don't think adding vuforia is productive towards the end goal of gm0, it would not be recommended for use by rookies anyway, and until it is more stable for use I don't see the point in adding this
