### ISSUE TITLE
Mention encoder model and maybe wheel model in the dead wheel gallery

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#149]
**What information should be added?**
Mention encoder model and maybe wheel model for each design in the dead wheel gallery

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
docs/robot-design/dead-wheels.html

**Comment by Eeshwar-Krishnan** [comment]
I don't know if this would be particularly useful, given that the examples either use not recommended sensors, or use rotacaster wheels with rev encoders
