### ISSUE TITLE
Mention common wheels on the dead wheel page

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#150]
**What information should be added?**
List common wheels for dead wheels

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
docs/robot-design/dead-wheels.html

**Comment by dansman805** [comment]
Probably a good idea to list a couple, should also probably talk about single vs double omni for odo

**Comment by NoahBres** [comment]
> Probably a good idea to list a couple with pros/cons, should also probably talk about single vs double omni for odo

What should be mentioned for single vs double?

**Comment by dansman805** [comment]
> What should be mentioned for single vs double?

Why single omni odometry doesn't work well, and how double omni alleviates those issues

**Comment by dansman805** [comment]
> What should be mentioned for single vs double?

Why single omni doesn't work well, and how double omni alleviates those issues

**Comment by Eeshwar-Krishnan** [comment]
Honestly, realistically, just about every odometry pod uses the same rotacaster 35mm omni wheels, so I don't know if this would ultimately be useful
