### ISSUE TITLE
Mention why "Stuck in stop" occurs

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#151]
**What information should be added?**
![Screen Shot 2021-02-12 at 9 13 02 AM](https://user-images.githubusercontent.com/6739076/107785689-839ee680-6d12-11eb-94f8-227366afe798.jpg)

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
Idk. One of the software pages about the SDK

**Comment by dansman805** [comment]
Maybe a "common issues" or something page, that would also work with https://github.com/Coppersource/gm0/issues/103

**Comment by Eeshwar-Krishnan** [comment]
I believe that https://gm0.org/en/latest/docs/software/common-issues.html#stuck-in-start-loop-stop addresses this
