### ISSUE TITLE
Misleading caption under Wiring Tips and Tricks

### ISSUE THREAD

**Issue by dansman805** [gamemanual0/gm0#160]
**Where is there misleading or incorrect information?**
https://gm0.org/en/stable/docs/power-and-electronics/tips-and-tricks.html#id1

**What's wrong?**
The order of the caption is misleading, as it is reverse from the image—it should probably read "An example Anderson PowerPole to XT30 adapter". It should also probably say something like "You can buy one from [ServoCity](https://www.servocity.com/anderson-powerpole-to-female-xt30-adaptor/) or [REV Robotics](https://www.revrobotics.com/REV-31-1385/)."

**Comment by NoahBres** [comment]
And label the caption. "An example of Anderson PowerPole (A) to XT30 (B) adapter"
