### ISSUE TITLE
Mention internal PID on PID Page

### ISSUE THREAD

**Issue by abidingabi** [gamemanual0/gm0#163]
**What information should be added?**
Bring up using internal PID. Also, talk about common issues with internal PID; namely why the motor would go at full speed regardless of setpoint. Solution: add encoder position to telemetry, if it's negative when setpoint motor is positive (or vice versa), the motor is plugged in backwards; if it's consistently 0/1 the encoder is not plugged in or is plugged in incorrectly.

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
Under the PID section of the Control Loops page: https://gm0.org/en/stable/docs/software/control-loops.html#pid

**Comment by dansman805** [comment]
Make sure to link to https://docs.revrobotics.com/rev-control-system/programming/using-encoder-feedback
