### ISSUE TITLE
Revamp Homepage

### ISSUE THREAD

**Issue by abidingabi** [gamemanual0/gm0#202]
The clickthrough rate from the homepage isn't very high, this likely has something to do with it's design. Maybe do something like [FRC Docs with sphinx panels](https://docs.wpilib.org/en/latest/index.html)? At least move the table of contents to the top, I don't know.

**Comment by colloquist** [comment]
See also: https://github.com/executablebooks/sphinx-design

**Comment by abidingabi** [comment]
Closed by https://github.com/gamemanual0/gm0/commit/cacc24ccf1fd492cef71949c2304bc511a6683df
