### ISSUE TITLE
Windows hates line endings (D004 issue)

### ISSUE THREAD

**Issue by Eeshwar-Krishnan** [gamemanual0/gm0#241]
**What's broken?**
Running `make lint` on windows leads to over 8000 errors because doc8 doesn't check carriage returns "properly" on windows

**Recreation steps:**

1. Run Windows 10
2. Download and setup repo
3. Run `make lint` and cry

![image](https://user-images.githubusercontent.com/32040858/180630206-0f0edbe0-0e8b-4bdd-b8be-d20793def14b.png)

Adding D004 would make it so that windows based editors don't go absolutely insane while trying to verify lint

Alternatively the solution of adding D004 to local lint ignore should be documented somewhere

**Comment by abidingabi** [comment]
Closed by https://github.com/gamemanual0/gm0/pull/243
