### ISSUE TITLE
"How the SDK handles exceptions" section has an inaccuracy, and is outdated

### ISSUE THREAD

**Issue by NoahAndrews** [gamemanual0/gm0#317]
**Where is there misleading or incorrect information?**
https://gm0.org/en/latest/docs/software/getting-started/common-issues.html?highlight=iterative#how-the-sdk-handles-exceptions

**What's wrong?**
An exception being thrown in an OpMode never required an app restart. It just required the Restart Robot option to be selected from the menu. In SDK 8.0 and later, selecting Restart Robot is no longer necessary either, and the full stacktrace is displayed onscreen.

**Comment by abidingabi** [comment]
Nice catch, thank you!
