### ISSUE TITLE
Change Github Actions to use Node.js v16

### ISSUE THREAD

**Issue by abidingabi** [gamemanual0/gm0#362]
The current workflows use Node.js v12 actions, which will be disabled on September 27th; see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. The workflows in this repository need to be updated, as well as those in the other repositories for this organization.

**Comment by ruthmumbe619** [comment]
I appreciate to be here

**Comment by abidingabi** [comment]
Done on other organization repositories.
