### ISSUE TITLE
Dead axle vs Live axle vs Zombie axle 

### ISSUE THREAD

**Issue by abidingabi** [gamemanual0/gm0#56]
**What information should be added?**
Info on benefits and cons of dead vs Live vs Zombie axle. 

**Does it need it's own page? (Yes/No):** Yes

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
Under power transmission

**Comment by dansman805** [comment]
Link to https://cad.onshape.com/documents/2251a809d55003f84441fb55/w/6806eec02ea42e983f352d28/e/6dcab250ae7ec70c0a1d3b59

**Comment by abidingabi** [comment]
Closed by https://github.com/gamemanual0/gm0/pull/229
