### ISSUE TITLE
Example code for runmodes

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#64]
**What information should be added?**
Write example code for runmodes. I specifically want to write samples for the setVelocity() arguments and lifting the max rpm fraction. Reference the document NPE dug up regarding the update rate on the velo controllers.
Also sample code for RTP and it's correct order, just to be safe.
More detailed explanation for brake mode (search for Tyler's explanation for how the motors short themselves and incorporate that information)

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
"Examples of using common hardware components" -> DC Motor -> runmodes

**Comment by NoahBres** [comment]
Mention how setPower() actually controls the max power in RTP. Default is zero so remember to set it.

**Comment by NoahBres** [comment]
Disclaimer that you probably shouldn't be using RUE for telex

**Comment by NoahBres** [comment]
Mention that setVelocity turns on velocity control regardless of whether or not you set RUE

**Comment by dansman805** [comment]
https://docs.revrobotics.com/rev-control-system/programming/using-encoder-feedback#choosing-a-motor-mode seems to cover this pretty well, linking to it is probably acceptable

**Comment by abidingabi** [comment]
it is now https://docs.revrobotics.com/duo-control/programming/using-encoder-feedback#choosing-a-motor-mode
