### ISSUE TITLE
Add info about Linkages 

### ISSUE THREAD

**Issue by abidingabi** [gamemanual0/gm0#71]
**What information should be added?**
Talk about linkages, basically rewrite https://gm0.org/en/stable/docs/robot-design/arms/chain-bar-arm.html.

Talk about 4 bars, v4bs, dr4bs, and custom ones (https://www.youtube.com/watch?v=QsAC_seQHJY, https://www.youtube.com/watch?v=I7iy8DCNmic).

**Does it need it's own page? (Yes/No):** Yes

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
Get rid of https://gm0.org/en/stable/docs/robot-design/arms/chain-bar-arm.html; basically rewrite it, probably put it under https://gm0.org/en/stable/docs/robot-design as `linkages`

**Comment by dansman805** [comment]
7236: https://photos.google.com/share/AF1QipNsu8Vfg-4-KyYrSDX7-a4W_sgyOntb-5_9M4EAdv7uX2K2Lyx7FMxCXlIEKTGjjg/photo/AF1QipNVndwFMIAyJQJ3KTjr46hzOLCEYAdOdzBEqvty?key=akRlbV9ZMG55U0otSkdWMUgwRUdWbXBxek1KcHBB

**Comment by dansman805** [comment]
https://blog.rectorsquid.com/linkage-mechanism-designer-and-simulator/
