### ISSUE TITLE
gm0 software section on button inputs

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#72]
**What information should be added?**
Specifically information on how to to read single button presses rather than just a constant boolean that returns true. Like an "isPressed" thing. I feel like this confuses beginners. 

**Does it need it's own page? (Yes/No):** 🤷 

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
🤷

**Comment by JIceberg** [comment]
It definitely is something that confuses people. Maybe just make a quick reference guide for input-handling that also references the reversed values on the sticks. Not sure about how that would be formatted/organized.

**Comment by dansman805** [comment]
I'd change Using the SDK into a section, put the current contents of it under a "Method Summary" or something, then write more detailed stuff under that (so have gamepad input be it's own page under Using the SDK).

**Comment by dansman805** [comment]
By making a "Using the SDK" section, you could move "Control System Internals" under it too, as the main point of it is largely to explain bulk reads.

**Comment by JIceberg** [comment]
> I'd change Using the SDK into a section, and put the current contents of it under a "Method Summary" or something, and then write more detailed stuff under that section (so have gamepad input be it's own page under Using the SDK).

#74 - I agree

**Comment by NoahBres** [comment]
Mention "Failling edge detector"

**Comment by dansman805** [comment]
Could should be straightforward, around like
```java
public void runOpMode() {
  private Gamepad previousGamepad1 = new Gamepad();
  private boolean toggleIntake = false;  
  
  while (opModeIsActive())
    if (gamepad1.a && !previousGamepad1.a) {
      // rising edge
    }

    if (!gamepad1.b && previousGamepad1.b) {
      // falling edge if you need that for some reason
    }

    if (gamepad1.x && !previousGamepad1.x) {
      toggleIntake = !toggleIntake; // rising edge detector that swaps toggle
    }

    // the actual toggle code
    if (toggleIntake) {
      // whatever
    }
    else {
      // the other thing
    }

    previousGamepad1.copy(gamepad1);
  }
}```

**Comment by dansman805** [comment]
A dedicated gamepad page should also probably include gamepad diagrams (see https://github.com/gamemanual0/gm0/issues/114)
