### ISSUE TITLE
Expand Upon Using the SDK

### ISSUE THREAD

**Issue by JIceberg** [gamemanual0/gm0#74]
**What information should be added?**
The current format fits closer to that of a pdf--which was the previous intent. There are still several concepts that need to be addressed as well as functionalities (like gamepad inputs).

**Does it need it's own page? (Yes/No):** Split it into subpages.

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
See above.

**Comment by dansman805** [comment]
Ideally, we'd have separate pages for:

* OpMode/LinearOpMode
* HardwareMap
* Motors
* Servos? idk if this is as necessary, maybe could share a spot with motors under an "actuators" page
* Gamepads
* Sensors (the following should be mentioned)
  * IMU
  * Digital
  * Analog
  * Maybe like the rev TOF and color sensor 
* Bulk reads (as part of control system internals)
* Method Summary (roughly in the style of the current page)? tbh i don't think this makes sense, but 🤷

**Comment by Eeshwar-Krishnan** [comment]
I think so far we have most of these, I mentioned in another issue that the SDK has example things for all of these so maybe a page about the SDK examples and grouping them with brief explanations of what they are/how to access could close the rest
