### ISSUE TITLE
Trig inverse kinematics for mecanum 

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#82]
**What information should be added?**
Trig inverse kinematics for mecanum. The current code only works for teleop which is great for beginners but preferably the angle method works a lot better for auto. So just addendum ig.
Also there's straight up no code for it online. 

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
Mecanum page

**Comment by dansman805** [comment]
Also see https://github.com/Coppersource/gm0/issues/58

**Comment by Eeshwar-Krishnan** [comment]
Closed by https://github.com/gamemanual0/gm0/pull/246
