### ISSUE TITLE
External encoders and programming them

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#86]
**What information should be added?**
Explain how external encoders plug into a motor encoder port and should be treated like a motor in the sdk.

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
Programming the sdk section?

**Comment by dansman805** [comment]
IMO, make a "sensor programming " page or something, cover encoders in general (CPR vs PPR, etc), have a subsection for motor encoders (go over run modes), and have a subsection for in external encoders (cover the stuff in parent, velocity overflow, and the encoder wrapper).

**Comment by JIceberg** [comment]
I have a sample for this in FTCLib. Should I make something similar using the SDK or do you want to use that as a sample? Might be useful to have a sample (code samples are useful of course!)
