### ISSUE TITLE
Basic time based auto sample

### ISSUE THREAD

**Issue by NoahBres** [gamemanual0/gm0#87]
**What information should be added?**
Basic sample of time based auto. `while(timer.seconds() < setTime) { move() }`
Explain why this isn't ideal but it does work fine as a first step. Also the fact that the while loops are blocking.

**Does it need it's own page? (Yes/No):** Yes

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
🤷‍♂️

**Comment by Eeshwar-Krishnan** [comment]
I kinda disagree with the addition of this page, given the sdk has examples for many things like this. Maybe instead a page linking the SDK examples and a brief explanation of them would be good, however that would have to be regularly maintained given the example are sometimes changed/renamed

**Comment by Eeshwar-Krishnan** [comment]
This is out of scope for gm0, sdk examples are linked to
