### ISSUE TITLE
Add a "Strategy" page

### ISSUE THREAD

**Issue by abidingabi** [gamemanual0/gm0#90]
**What information should be added?**
Add a "Strategy" page in the vein of Karthik's "Effective FIRST Strategies" talks; this overlaps somewhat with "Rookie Mistakes: Principles" somewhat, but maybe they could be merged? idk

**Does it need it's own page? (Yes/No):** Yes

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
Probably put it as the first page under https://gm0.org/en/stable/docs/getting-started-in-ftc/index.html? :shrug:

**Comment by dansman805** [comment]
Check out the game strategy section of https://media.githubusercontent.com/media/ftchistory/ftchistory.github.io/master/assets/seasons/2005-2006/robot-design.pdf

**Comment by dansman805** [comment]
In my opinion, It makes sense to prominently link to Karthik's talks and https://www.chiefdelphi.com/uploads/short-url/6JPbKQ6KXD2Qws2XEbaNttW15C3.pdf over wriitng something ourselves—probably in Rookie Mistakes: Principles?
